matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.2
language: java
script: mvn clean install -Dmaven.javadoc.skip=false
