language: java
sudo: false
before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
    - os: linux
      env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
    - os: linux
      env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
    - os: linux
      env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.3
script: ./mvnw clean install -Dmaven.javadoc.skip=false
