matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode8.3
language: java
script: mvn clean install -Dmaven.javadoc.skip=false
