name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_SECRET_KEY }}
           PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw -B package
